{% set name = "des-eastlake" %}
{% set version = "0.8.2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/des-science/eastlake/archive/refs/tags/{{ version }}.tar.gz
  sha256: a9867011d8715571d97973078a1742df14643b5420842112c70a49529e714028
  patches:
    - 0000_updated_autotools_guess.patch

build:
  # this recipe is not noarch due to using the scripts kwarg w/ setuptools
  skip: true  # [win]
  number: 0

requirements:
  build:
    - python                                 # [build_platform != target_platform]
    - cross-python_{{ target_platform }}     # [build_platform != target_platform]
    - {{ compiler('c') }}
    - make
    - gnuconfig  # [unix]
  host:
    - python
    - pip
    - setuptools_scm
    - setuptools_scm_git_archive
    - fftw
    - libtool
    - autoconf
    - automake
    - cfitsio
    # only builds against openblas
    - openblas
  run:
    - libblas * *openblas
    - libcblas * *openblas
    - liblapack * *openblas
    - liblapacke * *openblas
    - openblas
    - libopenblas
    - python
    - astropy
    - cfitsio  # for fpack and builds
    - des-desmeds >=0.9.17
    - des-pixcorrect
    - des-pizza-cutter-metadetect
    - esutil
    - fitsio
    - galsim
    - h5py
    - importlib_metadata
    - joblib
    - lsstdesc-coord
    - matplotlib-base
    - meds
    - metadetect
    - ngmix
    - numpy
    - numba
    - piff
    - pixmappy
    - psfex
    - pyyaml
    - scipy
    - setuptools
    - tqdm
  run_constrained:
    - des_montara >=0.7.0

test:
  imports:
    - eastlake
  commands:
    - eastlake-swarp -dd
    - eastlake-src-extractor -dd
    - run-eastlake-sim --help
    - python -c "import eastlake; assert eastlake.__version__ == '{{ version }}'"

about:
  home: https://github.com/des-science/eastlake
  license: BSD-3-Clause AND GPL-3.0-only
  license_file:
    - LICENSE
    - LICENSE-srcex
    - LICENSE-swarp
    - COPYRIGHT-srcex
    - COPYRIGHT-swarp
  summary: Y6 processing pipelines for balrog and image sims

extra:
  recipe-maintainers:
    - beckermr
